import Head from "next/head";
import { AnimatePresence } from "framer-motion";
import PreLoader from "@/_components/preloader";

export default function Home() {
  return (
    <>
      <Head>
        <title>Menath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main></main>
    </>
  );
}