import {
  Header, 
  Transition,
  NavigationBar,
} from '@/_layout';

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Menath</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Transition>
        <NavigationBar/>
          <Header/>
            <main>
              
            </main>
      </Transition>
    </>
  );
}